### ISSUE TITLE
Differentiate between top and bottom prev/next buttons

### ISSUE THREAD

**Issue by hagenw** [mgeier/insipid-sphinx-theme#148]
If a documentation contains a lot of short pages it looks a little bit weird that we have prev/next buttons at the top and the bottom, e.g.

![image](https://github.com/mgeier/insipid-sphinx-theme/assets/173624/f19345c7-9a90-464d-9a38-7e6252480a67)

One solution might be to automatically adjust if we present the buttons at the top depending on the page length.

An easier solution would be to provide different CSS classes for them so a user could write custom CSS code to hide one occurrences of the next/prev buttons. At the moment this is not possible as they are both added to the page with the `relbar` class. Maybe one could add an additional `top` and `bottom` class to them, e.g.

```html
<nav class="relbar top">
```

**Comment by mgeier** [comment]
The "relbars" can already be activated and deactivated individually using the `relbar1` and `relbar2` blocks, as shown in https://insipid-sphinx-theme.readthedocs.io/en/0.4.1/customization.html#custom-templates

This affects all pages, but you might be able to get per-page settings with some additional Jinja2 magic?

**Comment by hagenw** [comment]
Thanks, I overlooked this. It is indeed straightforward, the `_templates/layout.html` file just needs to contain:

```html
{% extends "!layout.html" %}

{% block relbar1 %}{% endblock %}
```

to disable the top next /prev buttons.

**Comment by mgeier** [comment]
Indeed, the `breadcrumbs` branch is an example for that: https://github.com/mgeier/insipid-sphinx-theme/compare/breadcrumbs^...breadcrumbs.

**Comment by hagenw** [comment]
The current solution seems fine to me. You can close this issue if you like as I don't think it is necessary to provide the functionality of automatically adjusting the visibility of the top and/or bottom prev/next buttons.
