### ISSUE TITLE
Consistently set FG and BG colors

### ISSUE THREAD

**Issue by AndydeCleyre** [mgeier/insipid-sphinx-theme#3]
Thanks for this theme! 

I don't know if this does now or plans to in the future support color schemes (or live scheme switching, as mdBook does), but looking at [the example](https://insipid-sphinx-theme.readthedocs.io/en/0.1.0/) it's apparent that in some places *one* of the FG *or* BG color is forced, while the other is left to the user's browser preference. This yields uncertain and potentially illegible results:

![image](https://user-images.githubusercontent.com/1787385/89484026-86b98880-d76b-11ea-94ae-bd559c4017b5.png)

If a FG or BG color is set, please also set the other, so that contrast can be ensured.

To reproduce in Firefox, set preferred FG and BG colors to light on dark:

![image](https://user-images.githubusercontent.com/1787385/89484279-29720700-d76c-11ea-81bd-abe2b921213f.png)

**Comment by mgeier** [comment]
Thanks for the report!

I have tried the suggested Firefox setting and found that setting FG and BG on the `<body>` seems to fix the problem, see #4.

Can you please check if that works for you?

Do I have to add anything else?

> I don't know if this does now or plans to in the future support color schemes (or live scheme switching, as mdBook does)

No, currently there is only one fixed color theme.
And yes, it would be great to have multiple color themes in the future.
And yes, it would be great to have live switching.

I've just created #5 to collect a few ideas, please feel free to contribute!

**Comment by AndydeCleyre** [comment]
Thanks! The body looks good on the rendered link in #4. The top bar and nav element FG is light, but that may be intentional.

![image](https://user-images.githubusercontent.com/1787385/89561620-c40f2c00-d7e6-11ea-8e5c-0215f5b56ee0.png)

**Comment by mgeier** [comment]
Thanks for checking this out!

> Thanks! The body looks good on the rendered link in #4. The top bar and nav element FG is light, but that may be intentional.

Yes, the light FG is intentional, it is supposed to get dark on hover.

But this, like everything, is of course open for discussion!
