### ISSUE TITLE
Font size becomes bigger when I tap on link

### ISSUE THREAD

**Issue by lsaffre** [mgeier/insipid-sphinx-theme#50]
I experience an irritating behaviour on the https://www.lino-framework.org/ website (which is build using insipid theme). It happens reproducibly on my Android phone (Ecosia and Chrome). Cannot reproduce it on any desktop browser.
When I tap on a link in the second paragraph of that page, I would expect that link to open. But instead, the font size becomes a bit bigger, causing the paragraph to reflow. I must tap a second time on the link to open it.
I will add a screencast of the behaviour to show you.

**Comment by lsaffre** [comment]
https://user-images.githubusercontent.com/4406823/121856200-e8883e80-ccfc-11eb-87d9-4e3c90cb41cb.mp4

**Comment by mgeier** [comment]
Thanks for the report!

This is very strange, though.

Unfortunately, I cannot reproduce it on my Android phone (I tried with Firefox and Chrome).

Does this only happen in paragraphs with external (i.e. underlined) links?

If yes, it might have something to do with this:

https://github.com/mgeier/insipid-sphinx-theme/blob/23e30fa443db648ea68a5c2b99637e05b41cdf16/src/insipid_sphinx_theme/insipid/static/insipid.css_t#L244-L247

**Comment by lsaffre** [comment]
Ha, that was a good hint! In my local copy of the insipid.css_t file (line 246) I changed the **border-bottom** of **a.external:hover** from **none** to **1px dotted #000000** and rebuilt the website, and now the strange behaviour has gone. Don't ask me why. Yes, it happened only in paragraphs with external links. I have Android version 10 QP1A.190711.020.

**Comment by lsaffre** [comment]
IOW I would be glad if you can do the same change in the official inispid.css_t because otherwise my problem would come back after my next insipid upgrade.

**Comment by mgeier** [comment]
Thanks for the update.

So the dotted line becomes black on hover?

Could you please make a PR?

**Comment by mgeier** [comment]
Changing the underline to black is barely visible, so I tried changing it to `transparent` instead: #51.

What do you think?
Does that work for you?
