### ISSUE TITLE
Menu should collapse on mobile device after selecting a page

### ISSUE THREAD

**Issue by lsaffre** [mgeier/insipid-sphinx-theme#53]
On a mobile device, when I tap the hamburger button top expand the menu, then tap one of the menu entries, insipid opens the related page but does not automatically also collapse the menu. Which is irritating on a mobile device because the menu takes the whole screen width and thus hides the content. I need to tap the hamburger button again (so that the menu collapses) in order to get to my page.

**Comment by lsaffre** [comment]
Matthias pointed out that (1) the issue is only for pages with a single title and (2) even then I can tap a second time on the same title to make the menu collapse. That's indeed already a quite satisfying workaround.

**Comment by mgeier** [comment]
Does #54 what you want?

It doesn't work on the main page if there are multiple links (like "Table of Contents" and the link in the logo), but on the other pages it should work as expected.

**Comment by lsaffre** [comment]
Yes, works perfectly for me! This is great!

**Comment by mgeier** [comment]
OK, thanks for testing, I've just made a new release 0.2.7 which includes this change.
