### ISSUE TITLE
Distance between h1 and previous/next buttons to large on mobile

### ISSUE THREAD

**Issue by hagenw** [mgeier/insipid-sphinx-theme#58]
When using the theme on a desktop the space between the main title and the next and previous buttons looks fine to me, but on a mobile it seems a little bit too much.

![image](https://user-images.githubusercontent.com/173624/133393718-237937c8-769b-4638-bfa5-7f084652c0fe.png)

**Comment by mgeier** [comment]
I agree.

I guess we could also reduce the space on wide screens.

We could probably remove (or reduce) the `padding-top` of `div.body`?

Please note that it is theoretically possible to have content before the first headline, see e.g. https://insipid-sphinx-theme.readthedocs.io/en/0.2.7/showcase/sections.html.

**Comment by mgeier** [comment]
BTW, there is a "breadcrumbs" option that should also be considered when changing the spacing.

I've just created a new branch with an example configuration that includes the "breadcrumbs" feature: https://insipid-sphinx-theme.readthedocs.io/en/breadcrumbs/

**Comment by mgeier** [comment]
I've created #71 to hopefully solve this issue.

I've also removed some space at the top *and* bottom of the previous/next links.

Is that enough?

**Comment by hagenw** [comment]
It now looks like this

![image](https://user-images.githubusercontent.com/173624/155947862-7e26f143-3755-4084-bec2-a8ae3157848c.png)

The distance is reduced from ~105 pixels to ~75 pixels.
I think this should be sufficient.

The space on top of the next and previous buttons is now slightly too small in my opinion, maybe you could reduce it by only half the current value?

**Comment by mgeier** [comment]
Yeah, I thought it would be OK, but now that you mention it, I see that the space is too small.

In b86bbabf65d3aff95c47e33e0dedbb2362bd2fed, I've kept the top padding and only removed the bottom padding.
What do you think about that?

Here's the preview: https://insipid-sphinx-theme--71.org.readthedocs.build/en/71/

**Comment by hagenw** [comment]
Yes, that looks good to me.

**Comment by mgeier** [comment]
OK, thanks, I've merged #71.
