### ISSUE TITLE
Hovering of links not consistent

### ISSUE THREAD

**Issue by hagenw** [mgeier/insipid-sphinx-theme#59]
Have a look at section 10.2:

![image](https://user-images.githubusercontent.com/173624/133397854-59a58be2-8378-442d-86eb-660efac063bb.png)

The default behavior for links in text is to show a dashed underline, which vanished when the mouse hovers offer it.
For the `hello_world()` link the behavior is opposite. If you hover with the mouse a non-dashed underline will appear.

I would vote for only showing a (dashed) line for links only when hovering with the mouse, this avoids also that pages look to cluttered.
Compare

![image](https://user-images.githubusercontent.com/173624/133398257-4e095be7-e12a-467b-ba4d-ce8f2ffad252.png)

with

![image](https://user-images.githubusercontent.com/173624/133398373-bc60066a-b014-444c-a464-8a82d3cb07fd.png)

**Comment by hagenw** [comment]
I think I got now the idea for the dashed underline:

![image](https://user-images.githubusercontent.com/173624/133498842-8b9a2a31-4020-4c6e-8c66-99ea24abab2e.png)

So, they should distinguish external from internal links.
I would still argue that it looks better without the underlines, but when staying with them there ist still a small inconsitency when hovering with the mouse. In that case I would propose that the dashed underlines should change to an actual line as this happens for the internal links as well.

**Comment by hagenw** [comment]
Another disadvantage of the dashed underlines for external links is that they don't work well together with badges:

![image](https://user-images.githubusercontent.com/173624/133499626-23799bc2-21ff-4db4-9c93-a54ba6ff273f.png)

**Comment by mgeier** [comment]
Yes exactly, this is intentional, I would like to be able to differentiate internal and external links.

Some themes use a special symbol at the end of links, but I would like to have something less disruptive.

It doesn't have to be an underline, we can maybe also use different colors?

Or do you have other ideas how to make them different?

The hover behavior is not that important to me, but they should look different when not hovering over them.

**Comment by mgeier** [comment]
I've just merged #63.

Does that resolve this issue, or are there other things we should change?

**Comment by hagenw** [comment]
I'm trying to test it, but after installing it with `pip install -e .`, and setting the theme in my project building it with

```bash
$ python -m sphinx docs/ build/html -b html
```
fails with
```
...
writing output... [ 14%] api                                                                                                                                                                   
Theme error:
An error happened in rendering the page api.
Reason: TemplateNotFound('icons/menu.svg',)
```

**Comment by hagenw** [comment]
Sorry, forgot:
```bash
$ git submodule update --init
```
as I'm on a new machine ;)

**Comment by hagenw** [comment]
Buttons are indeed fixed now:

![image](https://user-images.githubusercontent.com/173624/142187523-fcc04353-0eef-41e1-bfff-16e95bc028ea.png)

Hovering works now as expected. You could still call it inconsistent as it is different for internal and external links, but as they are also marked differently it behaves as a user would expect.

I will close the issue, thanks.
