### ISSUE TITLE
Line space could be increased

### ISSUE THREAD

**Issue by hagenw** [mgeier/insipid-sphinx-theme#60]
Compared with other themes the line spacing could maybe slightly increased to make it easier to read.

I created a comparsion for the API parameters section using https://audeering.github.io/audiofile/.
I haven't checked yet, if the same applys to all other sections.

**insipid**

![image](https://user-images.githubusercontent.com/173624/133500531-19fee0e4-fb21-439c-8472-fe4f6529fa35.png)

**RTD**

![image](https://user-images.githubusercontent.com/173624/133500728-386669c0-25a8-4a6c-b8c9-d8dbd162fa9b.png)

**typlog**

![image](https://user-images.githubusercontent.com/173624/133501660-04600d9a-d824-4270-919c-b2048680c0f3.png)

**Pure HTML (no CSS at all)**

![image](https://user-images.githubusercontent.com/173624/133501009-ec086c79-7fdf-4fc5-8c31-07c9e743ca05.png)

**Comment by mgeier** [comment]
I agree that the spacing should be increased, but not as much as in the other themes.

**Comment by mgeier** [comment]
I've created #74, which hopefully improves the situation shown above.

Is that enough space?

Is there anywhere else where space should be added?

**Comment by hagenw** [comment]
Thanks, it's enough and looks good.

**Comment by mgeier** [comment]
Thanks for checking this out. I've merged it and I'm closing this issue.

If there are other places with too little space, let me know!
