### ISSUE TITLE
Github repo does not show a "Used by" part

### ISSUE THREAD

**Issue by hagenw** [mgeier/insipid-sphinx-theme#69]
If you look at https://github.com/spatialaudio/python-sounddevice you will find

![image](https://user-images.githubusercontent.com/173624/151150880-fa0b549b-927a-443e-b3f3-a3011784e1fe.png)

This seems not to work for sphinx extensions as this (`insipid-sphinx-theme`) repo does not show this section and also https://github.com/hagenw/sphinxcontrib-katex (which is at least used by two other public Github repos) does snot show it.
Maybe the problem is that they are not listed as direct dependencies, but only as dependencies for the docs by other packages?

I think this is more a Github issue and not related to this repo, but before trying to figure out how to report it at Github, I wanted to note it down here.

**Comment by hagenw** [comment]
Strange, now I can also see it here on the landing page

![image](https://user-images.githubusercontent.com/173624/151152173-30354b84-dad5-4593-a015-c8737475a499.png)

**Comment by hagenw** [comment]
And now it is gone again:

![image](https://user-images.githubusercontent.com/173624/151152086-d26e1d46-b940-4fdb-ab72-cbf15724a558.png)

:)

**Comment by hagenw** [comment]
I think it is just a problem with presenting the dependencies in this project as they are all discovered, see https://github.com/mgeier/insipid-sphinx-theme/network/dependents,
where as for `sphinxcontrib-katex` no dependencies are discovered: https://github.com/hagenw/sphinxcontrib-katex/network/dependents

**Comment by mgeier** [comment]
I think this has something to do with Github's web server (load balancing or whatever). I often don't get the "Used by" section on first load, but when I reload a few times, it suddenly appears.

But, as you mentioned, the direct link https://github.com/mgeier/insipid-sphinx-theme/network/dependents works reliably.

As for why it doesn't work for https://github.com/hagenw/sphinxcontrib-katex, my hypothesis is that Github can handle the old-school `setup.py` quite well but doesn't yet fully support `setup.cfg` and similar newer technologies.

**Comment by hagenw** [comment]
Thanks for the input.
As it does not really affect https://github.com/mgeier/insipid-sphinx-theme as I first thought, feel free to close this issue.
