### ISSUE TITLE
Add a remark in CONTRIBUTING where to find preview HTML builds

### ISSUE THREAD

**Issue by hagenw** [mgeier/insipid-sphinx-theme#75]
As it is much faster to look at the results of a pull request in the online version than building it yourself it would be nice to mention the URL in `CONTRIBUTING`.

I'm talking about the following URLs:
`https://insipid-sphinx-theme--{id}.org.readthedocs.build/en/{id}/`, e.g. https://insipid-sphinx-theme--74.org.readthedocs.build/en/74/

**Comment by mgeier** [comment]
I think the best way to get to the right place is to click on the "Details" link of the RTD check.

Sadly, that's very non-obvious and a bit convoluted, but I agree that this should be added to the docs.

**Comment by mgeier** [comment]
Is #84 sufficient?

**Comment by mgeier** [comment]
#84 has been merged.
